/*
 * Copyright 2025 Etienne Payet <etienne.payet at univ-reunion.fr>
 *
 * This file is part of NTI.
 *
 * NTI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * NTI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with NTI. If not, see <https://www.gnu.org/licenses/>.
 */

package fr.univreunion.nti.program.lp.binaryunfolding;

import java.util.LinkedList;
import java.util.List;

import fr.univreunion.nti.program.lp.BinaryRuleLp;
import fr.univreunion.nti.program.lp.RuleLp;
import fr.univreunion.nti.program.lp.UnfoldedRuleLp;

/**
 * Finds complete recurrent pairs generated by binary unfolding.
 */
final class RecurrentPairLpFinder {

	/**
	 * This class cannot be instantiated.
	 */
	private RecurrentPairLpFinder() {}

	/**
	 * Finds the first complete recurrent pair generated by binary unfolding
	 * within the provided number of iterations.
	 *
	 * @param rules the rules of the logic program
	 * @param maxIterations the maximum number of unfolding iterations to run
	 * @return the first complete recurrent pair found, or <code>null</code>
	 * if none is found
	 * @throws InterruptedException if the current thread is interrupted
	 */
	static RecurrentPairLp findFirstComplete(
			Iterable<RuleLp> rules,
			int maxIterations) throws InterruptedException {
		LpBinaryUnfolder unfolder = new LpBinaryUnfolder(rules);
		List<RecurrentPairLp> candidates = new LinkedList<>();

		for (int iteration = 1; iteration <= maxIterations; iteration++) {
			RecurrentPairLp recurrentPair =
					findFirstCompleteInIteration(
							unfolder, iteration, candidates);
			if (recurrentPair != null)
				return recurrentPair;
		}

		return null;
	}

	/**
	 * Finds the first complete recurrent pair generated during one
	 * binary-unfolding iteration.
	 *
	 * @param unfolder the binary unfolder to advance
	 * @param iteration the unfolding iteration to compute
	 * @param candidates the recurrent-pair candidates accumulated so far
	 * @return the first complete recurrent pair found, or <code>null</code>
	 * if none is found during this iteration
	 * @throws InterruptedException if the current thread is interrupted
	 */
	private static RecurrentPairLp findFirstCompleteInIteration(
			LpBinaryUnfolder unfolder,
			int iteration,
			List<RecurrentPairLp> candidates)
			throws InterruptedException {

		List<UnfoldedRuleLp> unfolded = unfolder.unfoldNext(iteration);
		List<BinaryRuleLp> binaryRules =
				BinaryRuleLpSelector.selectFrom(unfolded);

		addUnitCandidates(binaryRules, candidates);

		return findFirstCompleteByExtendingCandidates(binaryRules, candidates);
	}

	/**
	 * Adds the recurrent-pair candidates obtained from single binary
	 * rules to the provided candidate list.
	 *
	 * @param binaryRules the newly generated binary rules
	 * @param candidates the recurrent-pair candidates to update
	 */
	private static void addUnitCandidates(
			Iterable<BinaryRuleLp> binaryRules,
			List<RecurrentPairLp> candidates) {
		for (BinaryRuleLp binaryRule : binaryRules)
			candidates.add(new RecurrentPairLp(binaryRule));
	}

	/**
	 * Finds the first complete recurrent pair obtained by adding one of
	 * the provided binary rules to an existing candidate.
	 *
	 * @param binaryRules the newly generated binary rules
	 * @param candidates the incomplete or complete recurrent-pair candidates
	 * @return the first complete recurrent pair found, or <code>null</code>
	 * if none is found
	 */
	private static RecurrentPairLp findFirstCompleteByExtendingCandidates(
			Iterable<BinaryRuleLp> binaryRules,
			Iterable<RecurrentPairLp> candidates) {
		for (BinaryRuleLp binaryRule : binaryRules) {
			for (RecurrentPairLp candidate : candidates) {
				RecurrentPairLp extendedCandidate = candidate.add(binaryRule);
				if (extendedCandidate != candidate &&
						extendedCandidate.isComplete())
					return extendedCandidate;
			}
		}

		return null;
	}
}
