/*
 * Copyright 2026 Etienne Payet <etienne.payet at univ-reunion.fr>
 *
 * This file is part of NTI.
 *
 * NTI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * NTI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with NTI. If not, see <https://www.gnu.org/licenses/>.
 */

package fr.univreunion.nti.program.lp.binaryunfolding;

import java.util.ArrayList;
import java.util.List;

import fr.univreunion.nti.program.lp.BinaryRuleLp;
import fr.univreunion.nti.program.lp.NonTerminationWitness;
import fr.univreunion.nti.program.lp.SoP;

/**
 * Builds unit nontermination witnesses from binary rules.
 *
 * <p>The construction is from E. Payet and F. Mesnard,
 * <a href="https://doi.org/10.1145/1119479.1119481">Non-Termination
 * Inference of Logic Programs</a>, ACM Transactions on Programming
 * Languages and Systems 28(2), 256--289, 2006.
 */
final class UnitWitnessBuilder {

	/**
	 * This class cannot be instantiated.
	 */
	private UnitWitnessBuilder() {}

	/**
	 * Implements the function <code>unitLoops</code> of Payet and Mesnard
	 * (2006), cited in the class documentation.
	 * <p>
	 * This method builds the unit nontermination witnesses contained in
	 * the given binary rules.
	 *
	 * @param binaryRules a list of binary unfolded rules
	 * @return the unit witnesses contained in <code>binaryRules</code>
	 */
	static List<NonTerminationWitness> buildFrom(
			Iterable<BinaryRuleLp> binaryRules) {
		// The witnesses to return at the end.
		List<NonTerminationWitness> newWitnesses = new ArrayList<>();

		// The thread running this proof.
		Thread currentThread = Thread.currentThread();

		for (BinaryRuleLp binaryRule : binaryRules) {
			if (currentThread.isInterrupted()) break;

			newWitnesses.addAll(buildFor(binaryRule));
		}

		return newWitnesses;
	}

	/**
	 * Builds the unit witnesses generated by one binary rule.
	 *
	 * @param binaryRule a binary unfolded rule
	 * @return the unit witnesses generated by <code>binaryRule</code>
	 */
	private static List<NonTerminationWitness> buildFor(
			BinaryRuleLp binaryRule) {
		List<NonTerminationWitness> witnesses = new ArrayList<>();

		List<BinaryRuleLp> binarySequence = unitSequenceFor(binaryRule);
		NonTerminationWitness loopingPair =
				tryBuildLoopingPairWitness(binaryRule, binarySequence);
		if (loopingPair != null)
			witnesses.add(loopingPair);

		witnesses.add(buildRecurrentPairWitness(binaryRule));

		return witnesses;
	}

	/**
	 * Tries to build the unit looping-pair witness generated by the
	 * given binary rule.
	 *
	 * @param binaryRule a binary unfolded rule
	 * @param binarySequence the unit binary sequence containing
	 * <code>binaryRule</code>
	 * @return the generated looping pair, or <code>null</code> if
	 * <code>binaryRule</code> is not a tau unit loop
	 */
	private static NonTerminationWitness tryBuildLoopingPairWitness(
			BinaryRuleLp binaryRule,
			List<BinaryRuleLp> binarySequence) {
		// We keep binaryRule for inferring loops from looping pairs.
		SoP tau = new SoP(binarySequence);
		if (binaryRule.isTauUnitLoop(tau))
			return new LoopingPair(binarySequence, tau);

		return null;
	}

	/**
	 * Builds the unit recurrent-pair witness generated by the given
	 * binary rule.
	 *
	 * @param binaryRule a binary unfolded rule
	 * @return the generated recurrent-pair witness
	 */
	private static NonTerminationWitness buildRecurrentPairWitness(
			BinaryRuleLp binaryRule) {
		// We also keep binaryRule for inferring binary chains
		// from recurrent pairs.
		return new RecurrentPairLp(binaryRule);
	}

	/**
	 * Builds the unit binary sequence containing the given binary rule.
	 *
	 * @param binaryRule a binary unfolded rule
	 * @return the unit binary sequence containing <code>binaryRule</code>
	 */
	private static List<BinaryRuleLp> unitSequenceFor(
			BinaryRuleLp binaryRule) {
		List<BinaryRuleLp> binarySequence = new ArrayList<>();
		binarySequence.add(binaryRule);
		return binarySequence;
	}
}
