/*
 * Copyright 2026 Etienne Payet <etienne.payet at univ-reunion.fr>
 *
 * This file is part of NTI.
 *
 * NTI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * NTI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with NTI. If not, see <https://www.gnu.org/licenses/>.
 */

package fr.univreunion.nti.program.recurrentpair;

import fr.univreunion.nti.term.Function;
import fr.univreunion.nti.term.Term;

/**
 * The components of a recurrent-pair certificate.
 *
 * @param u1 the left-hand side of the first finite chain
 * @param v1 the right-hand side of the first finite chain
 * @param u2 the left-hand side of the second finite chain
 * @param v2 the right-hand side of the second finite chain
 * @param c1 the context <code>c1</code>
 * @param c2 the context <code>c2</code>
 * @param s the term <code>s</code>
 * @param t the term <code>t</code>, either <code>s</code> or a variable
 * @param m1 the power <code>m1</code>
 * @param m2 the power <code>m2</code>
 * @param n1 the power <code>n1</code>
 * @param n2 the power <code>n2</code>
 * @param n3 the power <code>n3</code>
 * @param n4 the power <code>n4</code>
 * @param nonTerminatingTerm a nonterminating term generated by the recurrent pair
 */
record RecurrentPairData(
		Function u1,
		Function v1,
		Function u2,
		Function v2,
		Term c1,
		Term c2,
		Term s,
		Term t,
		int m1,
		int m2,
		int n1,
		int n2,
		int n3,
		int n4,
		Function nonTerminatingTerm) {

	/**
	 * Builds the recurrent-pair certificate components from the
	 * accepted search data.
	 *
	 * @param chains the finite chains of this recurrent pair
	 * @param root the leading function symbol of <code>c1</code> and its arity
	 * @param holePositions the selected hole positions
	 * @param firstChainParameters the parameters computed from the first chain
	 * @param secondChainParameters the parameters computed from the second chain
	 * @param nonTerminatingTerm a nonterminating term generated by the
	 * recurrent pair
	 * @return the recurrent-pair certificate components
	 */
	static RecurrentPairData from(
			FiniteChains chains,
			RootSymbol root,
			HolePositions holePositions,
			FirstChainParameters firstChainParameters,
			SecondChainParameters secondChainParameters,
			Function nonTerminatingTerm) {

		return new RecurrentPairData(
				chains.u1(),
				chains.v1(),
				chains.u2(),
				chains.v2(),
				holePositions.buildContext(root, chains.u1()),
				firstChainParameters.c2(),
				secondChainParameters.s(),
				secondChainParameters.t(),
				firstChainParameters.m1(),
				secondChainParameters.m2(),
				firstChainParameters.n1(),
				firstChainParameters.n2(),
				secondChainParameters.n3(),
				firstChainParameters.n4(),
				nonTerminatingTerm);
	}
}
