/*
 * Copyright 2026 Etienne Payet <etienne.payet at univ-reunion.fr>
 *
 * This file is part of NTI.
 *
 * NTI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * NTI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with NTI. If not, see <https://www.gnu.org/licenses/>.
 */

package fr.univreunion.nti.program.lp.binaryunfolding;

import static org.junit.jupiter.api.Assertions.*;

import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Path;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import fr.univreunion.nti.Options;
import fr.univreunion.nti.parse.ProgramFactory;
import fr.univreunion.nti.program.lp.Lp;

/**
 * Tests recurrent pairs generated by binary unfolding of logic programs.
 */
class RecurrentPairLpTest {

	private static String resourcePath(String resourceName) throws URISyntaxException {
		URL resource = RecurrentPairLpTest.class.getClassLoader().getResource(resourceName);
		assertNotNull(resource, () -> "Missing test resource: " + resourceName);
		return Path.of(resource.toURI()).toString();
	}

	@Test
	@DisplayName("test recurrent pair LP string representation")
	void recurrentPairLpToStringUsesLogicProgramWitnessFormat() throws Exception {
		RecurrentPairLp recurrentPairLp = buildRecurrentPairLp();

		assertEquals(
				"Recurrent pair: <[" +
				"p(_0,g(_1,h(0),_1)) :- p(_0,_1), " +
				"p(_2,[]) :- p(g(_2,h(0),_2),g(_2,h(0),_2)), " +
				"c1 = p(\u25a1,\u25a1'), " +
				"c2 = g(\u25a1,h(0),\u25a1), " +
				"s = [], " +
				"t = _2, " +
				"(m1,m2) = (1,0), " +
				"(n1,n2,n3,n4) = (0,0,1,1), " +
				"non-terminating query = p([],[])" +
				"> (Def.3 + Cor. 1 of [Payet, LOPSTR'25])",
				recurrentPairLp.toString());
	}

	@Test
	@DisplayName("find recurrent pair only within sufficient iterations")
	void findRecurrentPairOnlyWithinSufficientIterations() throws Exception {
		Lp lp = parseRecurrentPairLp();

		assertNull(RecurrentPairLpFinder.findFirstComplete(lp, 1));
		assertNotNull(RecurrentPairLpFinder.findFirstComplete(lp, 5));
	}

	private static RecurrentPairLp buildRecurrentPairLp() throws Exception {
		Lp lp = parseRecurrentPairLp();
		RecurrentPairLp recurrentPair =
				RecurrentPairLpFinder.findFirstComplete(lp, 5);
		assertNotNull(recurrentPair,
				"Aborting test: no complete recurrent pair found in LP!");
		return recurrentPair;
	}

	private static Lp parseRecurrentPairLp() throws Exception {
		String[] args = new String[] {
				resourcePath("examples/TC23/payet-nonloop-1_3.pl")
		};

		Options options = Options.parse(args);
		return (Lp) ProgramFactory.parse(options.getFileName());
	}
}
